### ISSUE TITLE
Configurable verbosity in Analyzer Status

### ISSUE THREAD

**Issue by jeremyfowers** [onnx/turnkeyml#113]
Problem: 
- the Analyzer orchestrates the analysis, build, and benchmarking of all the models in one file. It is typically invoked via the Files API, which in turn is typically invoked via the CLI.
- Analyzer has a module, `analyze.status`, which updates the terminal with progress. This status takes over the whole terminal, clearing it and updating it with information for all models across all files at each step.
- This status update system makes the CLI function like an application, which is great for demos and low numbers of models and files.
- It is not suitable for large numbers of models/files, or for direct use of the API, because it repeatedly prints full information for every model to the screen. This results in O(N^2) prints, which is not good from an API logging perspective.

Proposed solution: add verbosity modes to the status module that allow it to be configured for the following scenarios:
1. App mode: the way status currently works
2. Mass-evaluation mode: print status for each model exactly once, as that status becomes available. Don't clear the terminal. 
   - First print:  Model identified by analysis
   - Second print: Build status of model
   - Third print: Benchmark status of model
   - Also: show a TQDM-style status bar as we iterate over the files
3. Quiet mode: print minimal information (e.g., only the result requested by an API)

cc @danielholanda

**Comment by danielholanda** [comment]
Great feature suggestion. I also think we should decrease the verbosity of the App mode eventually, while still maintaining its ability to show `--max-depth` info. This, however, could be outside the scope of this PR.
