### ISSUE TITLE
Benchmark Status Shows Error when a previous Build Stage failed.

### ISSUE THREAD

**Issue by vgodsoe** [onnx/turnkeyml#137]
In the TKML Report, (turnkeyml==1.1.2), benchmark_status column currently shows:
- successful: when compilation passed, and the model successfully runs on hardware
- killed: when compilation passed but it fails running on hardware
- error: when the compilation stage or one of the previous stages failed.  <-- This one doesn't seem correct. 

I believe if one of the previous stages failed, benchmark status should show 'not_started', instead of 'error'.

**Comment by jeremyfowers** [comment]
I just tried to reproduce this on the head of TKML source code, and couldn't. My guess is the bug was in tkml 1.1.2 but has already been fixed. Let's monitor for the bug the next time we make a big report.

**Comment by danielholanda** [comment]
Should we close this issue?

**Comment by vgodsoe** [comment]
@danielholanda I think we wanted to monitor this in the next big report. When I get the 1.1 drop, I'll confirm and close it. :)
