### ISSUE TITLE
Refresh: No need for a stack trace when users provides no stages

### ISSUE THREAD

**Issue by danielholanda** [onnx/turnkeyml#175]
# Description

A full stack trace is shown when the user doesn't provide a stage name, which is not desirable.
This type of issue should behave similar to argparse errors. (no stack trace)

Example: `turnkey -i hello_world.py `

@jeremyfowers

**Comment by jeremyfowers** [comment]
This can be accomplished by calling `parser.error(msg)` instead of `raise Exception(msg)`.

**Comment by jeremyfowers** [comment]
Closed by #174
