### ISSUE TITLE
New naming scheme for stages

### ISSUE THREAD

**Issue by jeremyfowers** [onnx/turnkeyml#180]
Ideally there is a consistent naming scheme, and we can use the sequence in a sentence.

General rules:
- The word "onnx" should be assumed wherever possible since this is an ONNX toolchain
- Standard scheme is to name the tool as a verb that references the action it is taking
- Avoid using prepositions like "to"

Proposal:

- Anything that loads anything starts with `load-`
  - `load-build`
  - `load-onnx` (formerly `onnx-load`)
  - `load-llm-checkpoint`
- Anything that exports to ONNX should start with `export-SOURCE` since the "onnx" part is assumed
  - `export-pytorch` 
- ONNX-to-ONNX transformations should have the form `ACTION[-RESULT]` where `RESULT` optionally adds necessary detail to the action
  - `optimize` (formerly `optimize-onnx`)
  - `convert-fp16`
  - `quantize-int8`
- `discover`, `benchmark`: no change
- Compilation should use `compile-TARGET`, like `compile-ryzen-npu`

This allows for sequences-as-sentences like the following (with prepositions assumed):
- `discover` then `export-[to-]pytorch[-to-onnx]` then `optimize` then `quantize-[to-]int8` then `compile-[for-]ryzen-npu`

**Comment by jeremyfowers** [comment]
@danielholanda @ramkrishna2910 @vgodsoe please discuss

**Comment by danielholanda** [comment]
This looks like a great option and I honestly can't think of a better alternative.

I also like the idea of formalizing this as you are doing. Maybe there is even a part of the code where we check whether the specific stage in a plugin complies with our requirements.

**Comment by jeremyfowers** [comment]
Closed by #190
