### ISSUE TITLE
Remove `rebuild` argument at the CLI level

### ISSUE THREAD

**Issue by jeremyfowers** [onnx/turnkeyml#182]
@danielholanda please consider the following:

Back in the olden days, the `rebuild` argument was there to help manage the cache for users of the build API. We now have no one using the build API, so that has stopped being relevant.

In the TKML 1.0 era, the `rebuild` argument was primarily useful for "build once, benchmark elsewhere" workflows. However, we now have the `turnkey cache benchmark` command which is a much better way to benchmark a prebuilt model. `rebuild` has also stopped being relevant there.

In the TKML Refresh, commands are much more explicit. If I call `turnkey -i model.py discover export-pytorch` I expect it to do the thing! Not say "there was a cache hit, so I ignored your command." I find myself always using `rebuild=always` when I use TKML 2.0.

Finally, in TKML 2.0, it is easy to add a new front-end Stage along the lines of `load-build`, that would load a build from the cache and pass it to the next Stage. This would enable things like `turnkey -i cache/* load-build benchmark` to be a much more general replacement for `turnkey cache benchmark`

@danielholanda questions for you:
1. Can we get rid of the `rebuild` argument at the CLI level? My proposal is to set `rebuild=always` as the default at the CLI->build_api interface. We can keep `rebuild=if_needed` as the default in the build API.
2. Should we implement `load-build` and use it to phase out `turnkey cache benchmark`?

**Comment by jeremyfowers** [comment]
cc @danielholanda

**Comment by danielholanda** [comment]
yes, and yes. It is quite a change but `load-build` makes it worth it.
