### ISSUE TITLE
Reorganize the directory structure

### ISSUE THREAD

**Issue by jeremyfowers** [onnx/turnkeyml#185]
Problems:
 - Most of the stages in the `build.export` module are not export stages (e.g., OnnxLoad, OptimizeOnnxModel, Fp16Conversion). Move them, or rename the module?
 - The Report tool is sitting under the `cli` directory... when it's a tool
 - `discover` is the only stage that has its own directory

Proposed solution:
```
src/turnkeyml/
    |- tools
        |- tool.py (defines the `Tool`, `BuildTool`, and `ManagementTool` classes
        |- discover/
            |- discover_tool.py (defines `discover` tool)
            |- evaluate_script.py (defines `evaluate_script()`, the primary function of `discover`, currently named `script.py`)
        |- export.py (defines `export-pytorch` and `verify-onnx-exporter` tools)
        |- onnx.py (defines `onnx-load`, `optimize-onnx`, and `fp16-conversion` tools)
        |- report.py (defines `report` tool)
        |- cache.py (defines `cache` tool)
        |- version.py (defines `version` tool)
    |- toolchain
        |- toolchain.py (defines the `ToolChain/Sequence` class)
        |- ignition.py 
        |- stage_plugins.py
        |- build_api.py (defines `build_model()`)
        |- state.py (defines `State`, was in common/filesystem.py)
    |- common
        |- status.py (was in analysis/)
        |- everything currently in common
    |- run (unchanged... but will be removed shortly anyways)
```

**Comment by jeremyfowers** [comment]
@danielholanda @ramkrishna2910 please give any feedback or objections to this change

**Comment by danielholanda** [comment]
I would personally merge `discover_tool.py` and `evaluate_script.py` into a single script (`discover.py`) to create a more standardized folder structure. That being said, the proposed option is also good.

All other changes greatly improve clarity.

**Comment by jeremyfowers** [comment]
Great!

> I would personally merge discover_tool.py and evaluate_script.py into a single script (discover.py) to create a more standardized folder structure. That being said, the proposed option is also good.

I thought about this, but I was worried about file length. The discover tool is almost 300 lines and evaluate script is almost 500 lines, so the combined file would be almost 800 LoC.
