### ISSUE TITLE
Python support for >=3.11?

### ISSUE THREAD

**Issue by justinchuby** [onnx/turnkeyml#188]
I am trying to test turnkey-ml with https://huggingface.co/google/gemma-2-9b.

I am trying to do a pip install but got the following error:

`ERROR: Ignored the following versions that require a different python version: 0.3.0 Requires-Python >=3.8, <3.11; 1.0.0 Requires-Python >=3.8, <3.11; 1.1.0 Requires-Python >=3.8, <3.11; 1.1.1 Requires-Python >=3.8, <3.11; 1.1.2 Requires-Python >=3.8, <3.11; 1.1.3 Requires-Python >=3.8, <3.11; 2.0.0 Requires-Python >=3.8, <3.11; 2.0.1 Requires-Python <3.11,>=3.8; 2.0.2 Requires-Python <3.11,>=3.8; 2.0.3 Requires-Python <3.11,>=3.8`

Is Python>=3.11 supported?

@jeremyfowers

**Comment by jeremyfowers** [comment]
Hey Justin, sorry for the slow reply, I was on vacation. We just don't test with Python 3.11. Let me try making a branch and see if it works.

**Comment by jeremyfowers** [comment]
It looks like we have at least one dependency (scikitlearn 1.1.1) that isn't compatible with Python 3.11. I will take care of this as part of the bigger repo refresh I have been working on.
