### ISSUE TITLE
stages_completed is out of order in the report

### ISSUE THREAD

**Issue by jeremyfowers** [onnx/turnkeyml#35]
Stages attempted has the correct order: 

> ['export_pytorch', 'optimize_onnx', 'fp16_conversion', 'set_success']

Stages completed has the wrong order:

> ['export_pytorch', 'fp16_conversion', 'optimize_onnx', 'set_success']

This will cause some confusion when people look at the reports in Excel.

Suggested resolution: remove `stages_completed` from the report. We are already breaking out the member fields, and reporting success/fail, so including `stages_completed` is redundant and confusing.

cc @danielholanda

**Comment by danielholanda** [comment]
@jeremyfowers 

What about appending `stage_duration-` to the stage names in the report? This will also help to clarify what the information on those columns actually represent.

['stage_duration-export_pytorch', 'stage_duration-fp16_conversion', 'stage_duration-optimize_onnx', ...']
