### ISSUE TITLE
Fix flakey test: `timeout.py`

### ISSUE THREAD

**Issue by danielholanda** [onnx/turnkeyml#58]
# Description

`test_28_cli_timeout` doesn't always produce the same results given the same inputs. 

![image](https://github.com/onnx/turnkeyml/assets/9607530/71c480bf-97af-4740-9c8a-d52ea63047b6)

This test could benefit from adjustments to ensure it operates independently of the system it's on. Relying on approximate timeout allowances might not be the best approach for its reliability.

@jeremyfowers @ramkrishna2910

**Comment by jeremyfowers** [comment]
Fixed by the refresh!
