### ISSUE TITLE
Bug? / Wrong error message? "turnkey build bert.py"

### ISSUE THREAD

**Issue by andife** [onnx/turnkeyml#69]
Hi,
not sure if thats a bug?

Line 70 of the readme shows "turnkey build bert.py --sequence optimize-fp16"

I get the following:

```

(lightning_py310_231210) user1@hitssv565:/local_data/user1/models$ turnkey build rotational_power.py --sequence optimize-fp16

Error: Unexpected positional argument `turnkey build`. The first positional argument must either be an input file with the .py or .onnx file extension or one of the following commands: ['benchmark', 'cache', 'models', 'version'].

▄██████████████▄▐█▄▄▄▄█▌
██████▌▄▌▄▐▐▌███▌▀▀██▀▀
████▄█▌▄▌▄▐▐▌▀███▄▄█▌
▄▄▄▄▄██████████████


Traceback (most recent call last):
  File "/local_data/user1/miniforge3/envs/lightning_py310_231210/bin/turnkey", line 8, in <module>
    sys.exit(turnkeycli())
  File "/local_data/user1/miniforge3/envs/lightning_py310_231210/lib/python3.10/site-packages/turnkeyml/cli/cli.py", line 493, in main
    raise exceptions.ArgError(error_msg)
turnkeyml.common.exceptions.ArgError: Unexpected positional argument `turnkey build`. The first positional argument must either be an input file with the .py or .onnx file extension or one of the following commands: ['benchmark', 'cache', 'models', 'version'].

```

rotational_power.py contains a pytorch_lightning module? Does Turnkeyml work for lightning?

**Comment by jeremyfowers** [comment]
Apologies @andife the readme references a future command syntax that we have not yet included.

Instead of "turnkey build FILE" please try "turnkey benchmark FILE --build-only". 

I will fix the documentation issue you have pointed out. Thanks for filing an issue.

**Comment by andife** [comment]
Thanks. I'll try that. Are Pytorch lightning modules supported?

**Comment by jeremyfowers** [comment]
@andife the readme is fixed. 

With regards to PyTorch lightning: I’ll admit I wasn’t familiar with lightning, but fortunately I’m at neurips and was able to stop by their booth. 

The short answer is that no, Lightning modules are not supported. 

But it seems like it would be pretty straightforward to add support. If that’s something you would like, can you tell me a bit about your use case? I’d like to understand better.

**Comment by jeremyfowers** [comment]
There are really 3 problems here:
1. [FIXED] Documentation bug in the main README
2. The error message from that specific command is too confusing (user asked if it was an invalid input file, when in fact it was an invalid command)
3. PyTorch Lightning modules are not supported

I will close this issue, as the primary bug (documentation) has been fixed. And I will open issues for the other two.
