### ISSUE TITLE
Confusing error message on incorrect command

### ISSUE THREAD

**Issue by jeremyfowers** [onnx/turnkeyml#72]
# Problem Statement

The error message for an incorrect command to `turnkey COMMAND` is too confusing right now. This happens because the first positional argument can be either a file (in which case `COMMAND=benchmark` is assumed, ie `turnkey INPUT_FILES` == `turnkey benchmark INPUT_FILES) or an explicit command (ie, `turnkey COMMAND INPUT_FILES`).

The error message presents both of these possibilities, which is too broad of a decision space for new users.

# Example

An attempt to call `turnkey build INPUT_FILE` (which is not currently supported) results in this error message:

```
(lightning_py310_231210) user1@hitssv565:/local_data/user1/models$ turnkey build rotational_power.py --sequence optimize-fp16

Error: Unexpected positional argument `turnkey build`. The first positional argument must either be an input file with the .py or .onnx file extension or one of the following commands: ['benchmark', 'cache', 'models', 'version'].

▄██████████████▄▐█▄▄▄▄█▌
██████▌▄▌▄▐▐▌███▌▀▀██▀▀
████▄█▌▄▌▄▐▐▌▀███▄▄█▌
▄▄▄▄▄██████████████


Traceback (most recent call last):
  File "/local_data/user1/miniforge3/envs/lightning_py310_231210/bin/turnkey", line 8, in <module>
    sys.exit(turnkeycli())
  File "/local_data/user1/miniforge3/envs/lightning_py310_231210/lib/python3.10/site-packages/turnkeyml/cli/cli.py", line 493, in main
    raise exceptions.ArgError(error_msg)
turnkeyml.common.exceptions.ArgError: Unexpected positional argument `turnkey build`. The first positional argument must either be an input file with the .py or .onnx file extension or one of the following commands: ['benchmark', 'cache', 'models', 'version'].
```

# Proposed Solution

An arguments error in the first positional argument to `turnkey` should only ever present help for either an incorrect command OR an incorrect file path.

UI/UX:
- The error for `turnkey banchmerk model.py` should be: "command `banchmerk` is not a valid command, try CHOICES" (no mention of file inputs)
- The error for `turnkey cant_find_me.py` should be specifically about how a file with the supported file extensions could not be found (no mention of command choices)

Implementation: we will look for an indication that the first positional argument is either a command or a file path, and provide an appropriate error accordingly.
- If the special characters `*`, `\`, `/`, or `.` is present, we assume the argument is INPUT_FILES
- Otherwise, we assume the argument is COMMAND

cc @andife with regards to #69

**Comment by jeremyfowers** [comment]
@danielholanda can you review the implementation proposal and let us know if you are good with it?

**Comment by danielholanda** [comment]
The proposed implementation is definitely a great improvement!
