### ISSUE TITLE
Turnkey Stats records eval-specific stats at the model-level

### ISSUE THREAD

**Issue by jeremyfowers** [onnx/turnkeyml#79]
I run a benchmark of Model M on System A and then again on System B. The `system_info` key in the stats is recorded as a model-level stat, yet it is specific to one of these evaluations. 

Same thing for `onnx_model_information` (and maybe `onnx_ops_counter`?), since we could vary the ONNX opset across evaluations of the same model.

cc @danielholanda @ramkrishna2910

**Comment by jeremyfowers** [comment]
Or, we could say that one turnkey_stats.yaml always corresponds to one system. I don't think that constraint is stated explicitly anywhere right now, but if we did state it then no code changes are needed.

**Comment by danielholanda** [comment]
Not a blocker since we can post-process the CSV -> P2

**Comment by jeremyfowers** [comment]
Fixed by the refresh!
